# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.provision "docker"
  config.vm.box = "centos/7"

  config.vm.define "machine1" do |machine1|
    machine1.vm.network "private_network", ip: "172.16.8.1"
  end

  config.vm.define "machine2" do |machine2|
    machine2.vm.network "private_network", ip: "172.16.8.2"
  end

  config.vm.define "machine3" do |machine3|
    machine3.vm.network "private_network", ip: "172.16.8.3"
  end
end
